// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ousiaAPI.Data;

#nullable disable

namespace ousiaAPI.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20240602143905_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ousiaAPI.Model.Ply", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("angle")
                        .HasColumnType("float");

                    b.Property<string>("fiberOrientationAngle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("fiberOrientationMass")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("plyThickness")
                        .HasColumnType("float");

                    b.Property<double>("plyWeight")
                        .HasColumnType("float");

                    b.Property<string>("poissonRatio")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("shearModulus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("tensileModulus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("volumeFraction")
                        .HasColumnType("float");

                    b.Property<double>("weightFraction")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("Plies");
                });
#pragma warning restore 612, 618
        }
    }
}
